class Errors:
    error = {
        "-1": "Ya existe rol",
        "-2": "No existe rol",
        "-3": "Ya existe producto",
        "-4": "No existe el producto",
        "-5": "El producto ya está vencido, no se puede guardar un producto expirado",
        "-6": "El usuario ya existe",
        "-7": "El usuario no tiene permiso para realizar esta accion",
        "-8": "Usuario o clave incorrecta",
        "-9": "Cuenta desactivada",
        "-10": "Token no existe",
        "-11": "Token no valido",
        "-12": "Lote no existe",
        "-13": "No existen roles",
        "-14": "El usuario no existe",
        "-15": "La fecha de fabricación no puede ser una fecha futura. Por favor, ingrese una fecha valida",
        "-16": "La fecha de fabricación no puede ser posterior a la fecha de expiración. Por favor, verifique las fechas",
        "-17": "No existe archivo",
        "-18": "La extensión del archivo no es válida. Por favor, ingrese un archivo con extensión válida",
        "-19": "El Tamanio del archivo es superior al aceptado, el tamanio maximo es de 1MB",
        "-20": "Sucursal ya existe",
        "-21": "No existe sucursal",
    }
